language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - "python setup.py install"
    - "pip install curtsies greenlet pygments requests"

script:
    - cd build/lib/
    - "nosetests bpython/test"
